### ISSUE TITLE
A server error occurred.  Please contact the administrator.

### ISSUE THREAD

**Issue by bwheelz36** [ACRF-Image-X-Institute/scientific-method-app#93]
After following the instructions in the readme and launching the app, I just get a webpage saying "A server error occurred.  Please contact the administrator."

**Comment by Lilys-Code** [comment]
Updated readme instructions to reflect use of Docker. Running the project without Docker won't work because the secret_key comes from docker environment settings.

**Comment by Lilys-Code** [comment]
Sure thing! Will I be seeing you in person or at work?

**Comment by bwheelz36** [comment]
might have to be zoom.  when are you free?

**Comment by Lilys-Code** [comment]
I'm basically free all day until 5:00 so set up a time whenever you wish

**Comment by bwheelz36** [comment]
sent you a teams invite for 11.30
